---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    openshift.io/display-name: "Coolstore Shop"
    openshift.io/description: "Coolstore shopping cart application."
