---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
data:
  application.yaml: |-
    quarkus:
      kubernetes-client:
        trust-certs: true
      kubernetes-config:
        enabled: true
        config-maps:
        - {{ .Values.name }}-config
      hibernate-orm:
        database:
          generation: drop-and-create
        sql-load-script: load.sql
      datasource:
        db-kind: postgresql
        username: {{ .Values.database.username }}
        password: {{ .Values.database.password }}
        jdbc:
          url: {{ .Values.database.url }}
      log:
        level: INFO
