# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: gateway
image: quay.io/openshiftlabs/app-mod-gateway:1.1
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 512Mi

orders: my-orders
inventory: my-inventory
customers: my-customers
