apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order-placement.name" . }}
  labels:
    {{- include "order-placement.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  application.properties: |-
    mp.messaging.outgoing.order-event.bootstrap.servers={{ .Values.kafka.bootstrapServer }}
    mp.messaging.outgoing.order-event.topic={{ .Values.kafka.orderEventTopic }}

    {{ if .Values.kafka.securityProtocol }}
    mp.messaging.connector.smallrye-kafka.security.protocol={{ .Values.kafka.securityProtocol }}
    {{ end }}
    {{ if .Values.kafka.saslMechanism }}
    mp.messaging.connector.smallrye-kafka.sasl.mechanism={{ .Values.kafka.saslMechanism }}
    {{ end }}

    {{ if eq .Values.kafka.saslMechanism "PLAIN" }}
    mp.messaging.connector.smallrye-kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
      username="{{ .Values.kafka.userId }}" \
      password="{{ .Values.kafka.password }}" ;
    {{ end }}