# Default values for customers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: customers
image: quay.io/openshiftlabs/app-mod-customers:1.0
database:
  name: customers-db
  url: jdbc:postgresql://customers-db:5432/customers-db
  username: redhat
  password: redhat
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 512Mi
