---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
data:
  application.yaml: |-
    services:
      orders:
        url: http://{{ .Values.orders }}:8080/orders
      inventory:
        url: http://{{ .Values.inventory }}:8080/products
      customers:
        url: http://{{ .Values.customers }}:8080/customers-tomcat-0.0.1-SNAPSHOT/customers
    hystrix:
      command:
        ProductsCall:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 2000
      threadpool:
        ProductsThreads:
          coreSize: 20
          maxQueueSize: 200
          queueSizeRejectionThreshold: 200
