kind: Secret
apiVersion: v1
metadata:
  name: {{ include "catalog-db.name" . }}
  labels:
    {{- include "catalog-db.labels" . | nindent 4 }}
  annotations:
    {{- include "catalog-db.argocd-syncwave" . | nindent 4 }}
stringData:
  database-user: {{ .Values.pgsql.user }}
  database-password: {{ .Values.pgsql.password }}
  database-name: {{ .Values.pgsql.database }}
type: Opaque
