# Default values for coolstore-office.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

postgresql:
  databases:
    - name: inventory-db
      username: redhat
      password: redhat
    - name: orders-db
      username: redhat
      password: redhat
    - name: customers-db
      username: redhat
      password: redhat

customers:
  name: customers

inventory:
  name: inventory

orders:
  name: orders

gateway:
  name: gateway
  orders: orders
  inventory: inventory
  customers: customers

frontend:
  name: frontend
  gateway: gateway
