---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    openshift.io/display-name: "Coolstore Office"
    openshift.io/description: "Coolstore backoffice application."
