---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ui
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None
