---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    deployment: {{ .Values.name }}
