---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
type: Opaque
stringData:
  persistence.properties: |-
    jdbc.driverClassName=org.postgresql.Driver
    jdbc.url={{ .Values.database.url }}
    jdbc.user={{ .Values.database.username }}
    jdbc.password={{ .Values.database.username }}
    hibernate.hbm2ddl.auto=create-drop
    hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    management.endpoint.health.show-details="always"
    management.endpoint.health.show-components="always"
    management.endpoint.health.probes.enabled=false
