# Default values for inventory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: inventory
image: quay.io/openshiftlabs/app-mod-inventory:1.0
database:
  name: inventory-db
  url: jdbc:postgresql://inventory-db:5432/inventory-db
  username: redhat
  password: redhat
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 512Mi
