apiVersion: v1
kind: Service
metadata:
metadata:
  name: {{ include "catalog-service.name" . }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ .Values.service.portName }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.ports.httpPortName }}
  selector:
    {{- include "catalog-service.selectorLabels" . | nindent 4 }}
