---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
type: Opaque
stringData:
  application.yaml: |-
    spring:
      datasource:
        username: {{ .Values.database.username }}
        password: {{ .Values.database.password }}
