nameOverride: "kafka"

kafka:
  version: 3.5.0
  cluster:
    replicas: 3
  zookeeper:
    replicas: 3
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 3
    offsetsTopicReplicationFactor: 3
    transactionStateLogReplicationFactor: 3
    transactionStateLogMinIsr: 2
    minInsyncReplicas: 2
    interBrokerProtocolVersion: '3.5'

argocd:
  enabled: true
  syncwave: "-2"
