apiVersion: v1
kind: Service
metadata:
  name: {{ include "inventory-db.name" . }}
  labels:
    {{- include "inventory-db.labels" . | nindent 4 }}
  annotations:
    {{- include "inventory-db.argocd-syncwave" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.service.portName }}
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.ports.pqsqlPortName }}
  selector:
    {{- include "inventory-db.selectorLabels" . | nindent 4 }}
