nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image: 
  repository: quay.io/globex-recommendation/catalog-database
  pullPolicy: IfNotPresent
  tag: "0f2bc23"

ports:
  pqsqlPortName: postgresql
  pgsqlPort: 5432

securityContext: {}
  # for OpenShift 4.11:
  # allowPrivilegeEscalation: false
  # runAsNonRoot: true
  # seccompProfile:
  #   type: RuntimeDefault
  # capabilities:
  #   drop:
  #     - ALL

podAnnotations: {}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  tcpSocket:
    port: 5432

readinessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  exec:
    command:
    - "/bin/sh"
    - "-i"
    - "-c"
    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'

service:
  portName: postgresql
  port: 5432

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

pgsql:
  user: catalog
  password: catalog
  database: catalog

argocd:
  enabled: true
  syncwave: "-2"
