nameOverride: inventory
fullnameOverride: ""

replicaCount: 1

image:
  repository: quay.io/globex-recommendation/inventory
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "6500629"

podAnnotations: {}

ports:
  httpPortName: http
  httpPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 250Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /q/health/live
    port: http
    scheme: HTTP
  initialDelaySeconds: 30
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /q/health/ready
    port: http
    scheme: HTTP
  initialDelaySeconds: 5
  timeoutSeconds: 3
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

route:
  enabled: false
  host:
  tlsEnabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

service:
  portName: http
  port: 8080

securityContext: {}
  # for OpenShift 4.11:
  # allowPrivilegeEscalation: false
  # runAsNonRoot: true
  # seccompProfile:
  #   type: RuntimeDefault
  # capabilities:
  #   drop:
  #     - ALL

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

inventoryDb:
  name: inventory-db
  secret:
    name: inventory-db
