# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: frontend
image: quay.io/openshiftlabs/app-mod-ordersfrontend:1.0
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

gateway: my-gateway
